### ISSUE TITLE
Better error message when continuation run can't find RunMetaData etc.

### ISSUE THREAD

**Issue by ncollier** [carolyner/imabc#36]
Small thing but I mis-specified the previous_results_dir as an existing directory that did not contain the RunMetaData etc. files from the previous run. The error message says only that the directory is not a file and so cannot be read. Better might be that if the RunMetaData etc. files aren't found then, something like `paste0("Can't find RunMetData etc. in ", previous_results_dir)`

**Comment by cmaerzluft** [comment]
In main branch
