### ISSUE TITLE
as.targets example in README.md uses incorrect data.frame column names

### ISSUE THREAD

**Issue by jozik** [carolyner/imabc#37]
README.md has the following example listed for creating targets from a data.frame, but the column names appear to not be correct

# df <- data.frame(
#   group = c("G1", "G2", "G1"), name = c("T1", "T1", "T2"), target = c(1.5, 0.5, -1.5),
#   lower_bounds_start = c(1, 0.2, -2), upper_bounds_start = c(2, 0.9, -1),
#   lower_bounds_stop = c(1.49, 0.49, -1.51), upper_bounds_stop = c(1.51, 0.51, -1.49)
# )
# ex <- as.targets(df)

**Comment by cmaerzluft** [comment]
Removed this from the README. This way the README is just a brief introduction and there are fewer things that can change/require updating. The help file for as.targets has a correct example
