### ISSUE TITLE
SimulatedDistances_XXX.csv   SimulatedParameters_XXX.csv  SimulatedTargets_XXX.csv only track the last iteration

### ISSUE THREAD

**Issue by jozik** [carolyner/imabc#41]
In previous versions the SimulatedDistances_XXX.csv   SimulatedParameters_XXX.csv  SimulatedTargets_XXX.csv files tracked all the iterations that were part of the current run. But in the ratchet branch tests we're seeing that only the last iteration is being tracked. As far as I could tell there were no very recent code changes that modified the behavior so this could have been a change that was done between the imabc package submission and now.

**Comment by cmaerzluft** [comment]
This is the same problem from issue #43
