### ISSUE TITLE
Extra column in GoodSimulated*.csv crashes continuations

### ISSUE THREAD

**Issue by ncollier** [carolyner/imabc#44]
The 3 GoodSimulation files have a new column “actual_iter” that makes the code fail in various places. For example, the check that the names in priors and targets match those in GoodSimulatedParameters and GoodSimulatedTargets fails because “actual_iter” isn’t in the vector of standard columns removed from the Good data frames.

Possible workaround / fix in 01158c91771fee31df172e30c177418481b135ef

**Comment by cmaerzluft** [comment]
You shouldn't need to do both. I will add the code you suggested in the read_previous_results code to make sure it is not read into imabc.
