### ISSUE TITLE
Crash at Continuation Start

### ISSUE THREAD

**Issue by ncollier** [carolyner/imabc#45]
On the interim_good_outputs branch (itself a branch of ratchet), imabc is crashing at the start of a continuation with this error:

```R
Error in if (sigma[center_id, x] != 0) { : argument is of length zero
In addition: Warning messages:
1: replacing previous import 'vctrs::data_frame' by 'tibble::data_frame' when loading 'dplyr' 
2: In (function (target_fun, priors = NULL, targets = NULL, N_start = 1,  :
  priors object provided is ignored in favor of priors object derived from previous results.
3: In (function (target_fun, priors = NULL, targets = NULL, N_start = 1,  :
  targets object provided is ignored in favor of targets object derived from previous results.
4: In iter_target_dist$step[1:n_draw] <- as.integer(new_steps) :
  number of items to replace is not a multiple of replacement length
5: In iter_sim_target$step[1:n_draw] <- iter_target_dist$step[1:n_draw] <- as.integer(new_steps) :
  number of items to replace is not a multiple of replacement length
6: In iter_parm_draws$step[1:n_draw] <- iter_sim_target$step[1:n_draw] <- iter_target_dist$step[1:n_draw] <- as.integer(new_steps) :
  number of items to replace is not a multiple of replacement length
7: In matrix(0.5 * prior_sds, ncol = n_parms, nrow = num_centers, byrow = TRUE) :
  data length exceeds size of matrix
12: (function () 
    traceback(2))()
11: FUN(X[[i]], ...)
10: lapply(parm_names, FUN = function(x, n, mu, sigma, lower, upper) {
        if (sigma[center_id, x] != 0) {
            rtruncnorm(n, a = lower[x], b = upper[x], mean = mu[center_id, 
                x], sd = sigma[center_id, x])
        }
        else {
            rep(mu[center_id, x], n)
        }
    }, n = n_add, mu = mu, sigma = sigma, lower = lower_bounds, upper = upper_bounds)
9: `[.data.table`(draws, , `:=`((parm_names), lapply(parm_names, 
       FUN = function(x, n, mu, sigma, lower, upper) {
           if (sigma[center_id, x] != 0) {
               rtruncnorm(n, a = lower[x], b = upper[x], mean = mu[center_id, 
                   x], sd = sigma[center_id, x])
           }
           else {
               rep(mu[center_id, x], n)
           }
       }, n = n_add, mu = mu, sigma = sigma, lower = lower_bounds, 
       upper = upper_bounds)), by = center_id)
8: draws[, `:=`((parm_names), lapply(parm_names, FUN = function(x, 
       n, mu, sigma, lower, upper) {
       if (sigma[center_id, x] != 0) {
           rtruncnorm(n, a = lower[x], b = upper[x], mean = mu[center_id, 
               x], sd = sigma[center_id, x])
       }
       else {
           rep(mu[center_id, x], n)
       }
   }, n = n_add, mu = mu, sigma = sigma, lower = lower_bounds, upper = upper_bounds)), 
       by = center_id]
7: draw_parms(n_add = Center_n, mu = center_next[, all_parm_names], 
       sigma = sd_next, priors_list = priors)
6: eval(jsub, SDenv, parent.frame())
5: eval(jsub, SDenv, parent.frame())
4: `[.data.table`(iter_parm_draws, 1:n_draw, `:=`((all_parm_names), 
       draw_parms(n_add = Center_n, mu = center_next[, all_parm_names], 
           sigma = sd_next, priors_list = priors)))
3: iter_parm_draws[1:n_draw, `:=`((all_parm_names), draw_parms(n_add = Center_n, 
       mu = center_next[, all_parm_names], sigma = sd_next, priors_list = priors))]
```

I've attached the csv files I'm restarting from. So, hopefully, this can be reproduced. The IMABC parameters are:

```R
imabc.args = list(
        target_fun = NULL,
        previous_results_dir = '/lus/eagle/projects/ModelCRC/cisnet_calib/simcrc/experiments/imabc_ratchet_1.2b',
        N_start = 29000,
        # N_start = 60,
        seed = 12345,
        latinHypercube = TRUE,
        N_centers = 10,
        Center_n = 1600,
        N_post = 2000,
        max_iter = 2,
        N_cov_points = 250,
        sample_inflate = 2,
        verbose = TRUE,
        output_tag = "timestamp",
        improve_method = "gtbr"
    )
```

[restart_files.zip](https://github.com/carolyner/imabc/files/7032168/restart_files.zip)

**Comment by cmaerzluft** [comment]
@ncollier, Could you go into more detail about how you got the files in the attached zip folder? 

Ultimately, this is an issue because there are technically no good points in the good_distance file as imabc defines a good point. If you look at the n_good column, you will see that there are only values of 0 and 13. However, since there are 14 targets, imabc() requires n_good to equal 14 in order for a parameter set to be considered good. This is leading to trouble down the function.

Oddly though, all the points in good_distance seem to actually be good when evaluated against the provide target list. I'm not sure why that would happen, so I am hoping some more detail could clear it up.

Regardless, one thing that can help us avoid this in the future is to evaluate distances from a previous run when we load them into R (and cause an error if no good points are found). I have push a change to your new branch that will do this.

**Comment by ncollier** [comment]
@cmaerzluft the files are from a continuation on the interim_good_outputs branch. We began with an LHS (labeled 1.0), then did continuation of the LHS which we called 1.1b, and then a continuation of 1.1b, called 1.2b. When we tried to continue 1.2b, we get the crash above. So, the files are  those produced by the 1.2b run. These are the runs and the total number of iterations.

LHS (1.0) -> 1.1b, 2 iters -> 1.2b,  8 iters -> crash.

**Comment by jozik** [comment]
> Oddly though, all the points in good_distance seem to actually be good when evaluated against the provide target list. I'm not sure why that would happen, so I am hoping some more detail could clear it up.

Chris, what would lead to what looks like an error in outputting the good_distance file? I see that your fix would side step this issue, but I'm a little concerned that any issue in good_target_dist might affect the algorithm itself, not just for continuation purposes. Any ideas?

**Comment by cmaerzluft** [comment]
Were the input specs the same for all runs (except for the fact that the continuation runs had the previous inputs specified? I am specifically curious if max_iter was changed between runs.

**Comment by jozik** [comment]
Yes, max_iter was changed between runs.

And yes, I believe we don't save iteration results other than in those lines, specifically here: https://github.com/carolyner/imabc/blob/interim_good_outputs/R/imabc.R#L1069
