### ISSUE TITLE
Produce interim outputs for different verbosity levels

### ISSUE THREAD

**Issue by jozik** [carolyner/imabc#46]
We had discussed using different verbosity flags to output different levels of interim outputs.

For reference, Nick and I have been outputting the following interim outputs:

- Good_SimulatedParameters_<output_tag>
- Good_SimulatedTargets_<output_tag>
- Good_SimulatedDistances_<output_tag>
- CurrentTargets_<output_tag>

into an interim_output_<output_tag> directory, see 058c669

**Comment by cmaerzluft** [comment]
@ncollier created interim_good_outputs. Added to dev branch
