### ISSUE TITLE
Address "stuck" algorithm that fails to update bounds on consecutive steps

### ISSUE THREAD

**Issue by carolyner** [carolyner/imabc#49]
Observed behavior: the algorithm can become stuck and fail to update target bounds. 

Planned solution: 
1. Add a counter (n_cons_fail_update) that tracks the number of times the algorithm has enough draws to update the bounds, but is unable to update bounds. Initialize n_cons_fail_update to zero and reset to zero each time bounds are updated.

2. End the algorithm when it n_cons_fail_update > a user-specified number of consecutive iterations  with enough good draws to update bounds (line 639: current_good_n >= improve_min_samplefactor*N_cov_points),

**Comment by carolyner** [comment]
I think there is an issue in code lines 589/628 of imabc.R, in the manual_sample branch.  

I step through it below.

https://github.com/carolyner/imabc/blob/a15b5584ed96c9101ef1264ea71ad0c063768846/R/imabc.R#L591

- n_store is the maximum number of good points retained across iterations 
- current_good_n is the number of good points that the algorithm has found up to this iteration
- iter_valid_n is the number of good points newly identified in the current iteration
- n_keep is the number of points that the algorithm has found so far that are retained when storage is exceeded.

if(main_loop_iter==1) n_keep=iter_valid_n  This assumes that storage is never exceeded on the very first iteration. While unlikely, this is possible, so this condition should be removed.

if(main_loop_iter>1 & (n_current_good+iter_valid_n)<=n_store)) this means storage hasn't been exceeded, and we set n_keep = iter_valid_n

if(main_loop_iter>1 & (n_current_good+iter_valid_n)>n_store)) then storage has been exceeded and we  set n_keep = (n_store - iter_valid_n). This means we keep all of the newly identified good points, sacrificing previously identified good points  at least that is the intention.  

The points that are retained are those nearest to the bounds, based on the tot_dist, the total scaled distance.  **This ensures that we will continue to sample in the same general region, which may be problematic. **

I would like a closer look at this code, to determine if it is in fact acting the way expected. It appears that the previous draws are being favored/retained and the new draws are being thrown out. This would explain the complete lack of updating of draws after the algorithm reaches a certain point.

There are many alternatives to the approach taken. However, a good approach would probably be some combination of: calculating a distance that is ONLY based on targets with bounds that have not reached the stopping points AND figuring out a way to sort both the existing n_current_good in-range draws and new iter_valid_n  in-range draws to choose the n_store best OVERALL draws, rather than prioritizing either the current or past draws.  I couldn't figure out how to do this and this approach did not cause problems at past iters, but this clearly needs to be resolved.

**Comment by carolyner** [comment]
Note that the proposed solution that uses dist_updating, is an extension of #51, "Test alternative distance calculations for bound narrowing".  I am closing #51.

@cmaerzluft Revise code to implement sampling using dist_updating as an option, to facilitate testing and comparison of approaches. As noted above, dist_updating would be used for ordering of best points in the good_ objects to identify "best" points, including identification of centers around which points are sampled.

**Comment by cmaerzluft** [comment]
Code was already calculating the distance like dist_updating. Added comments to highlight this
Added n_cons_fail_update input in develop branch push:  https://github.com/carolyner/imabc/commit/6e11431b0ab4ae1aedd524a0a514db7c588f7099
tests all passed.
