### ISSUE TITLE
direct method: allow fewer points to be thrown out when narrowing bounds

### ISSUE THREAD

**Issue by carolyner** [carolyner/imabc#55]
Line [706](https://github.com/carolyner/imabc/blob/7bd6b550efc6d69441079aa0efd5d4e9b9bb8128/R/imabc.R#L706)
ratchet_levels <- seq(1, 0.05, -0.05)
 
 
These “rachet_levels” are passed to get_new_bounds, and refer to how we update the bounds.  This is very similar to our prior approach, which was based on updating bounds using a confidence interval approach based on increasing the alpha-level at each step. This has the effect of taking bigger steps initially, then smaller steps we move further away from the tails.

Suggested change:
 
ratchet_levels <- c(seq(1, 0.05, -0.05),0.025,0.01,0.001)
 
This allow small steps toward the final bounds when the algorithm is struggling.  Note that the direct approach updates all target bounds by the same amount, and this could cause issues when using the direct method and setting some target to have very wide bounds to allow acceptance of many points.

**Comment by cmaerzluft** [comment]
@carolyner pushed changes to dev
