### ISSUE TITLE
Add a distance-based tiebreaker when identifying best points

### ISSUE THREAD

**Issue by carolyner** [carolyner/imabc#58]
Best points are those that are closest to targets, and the ordering of points is used to determine both centers and the points that are excluded when attempting to narrow bounds.

When using the maximum Z-score, several parameter vectors have the same value for tot_dist. Because of this, we need to break ties using the weighted Euclidean distance.  

Proposed solution
1.	add a new euclid_dist column, weighted if a scale is provided. When the algorithm is updating tolerance bounds, euclid_dist would be based on the distance from targets with bounds that are still being updated. Once all target bounds have been reached, euclid_dist would be based on all targets.
2.	use total_distance() to calculate euclid_dist
3. use euclid_dist as a tiebreaker when narrowing tolerance bounds, [line 667](https://github.com/carolyner/imabc/blob/c799c43a9900e952e4a556b374d8d74c58d0cb23/R/imabc.R#L667): add sort by euclid_dist
4. use euclid_dist as a tiebreaker when selecting centers, [line 887](https://github.com/carolyner/imabc/blob/c799c43a9900e952e4a556b374d8d74c58d0cb23/R/imabc.R#L887): add sort by euclid_dist

**Comment by cmaerzluft** [comment]
added code with: https://github.com/carolyner/imabc/commit/d0d195fb76fc029d27435cb0200f8faf3e32fdfc
